version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=doc_manager
      - JWT_SECRET=your_super_secret_key_here
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=doc_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: